5   PRINT TAB(33);"BAGELS"
10   PRINT TAB(15);"CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY" : PRINT  : PRINT
15   REM *** BAGLES NUMBER GUESSING GAME
20   REM *** ORIGINAL SOURCE UNKNOWN BUT SUSPECTED TO BE
25   REM *** LAWRENCE HALL OF SCIENCE, U.C. BERKELY
30   DIM A1(6) : DIM A(3) : DIM B(3)
40   Y=0 : T=255
50   PRINT  : PRINT  : PRINT
70   INPUT "WOULD YOU LIKE THE RULES (YES OR NO)";A$
90   IF LEFT$(A$, 1)="N" THEN 150
100   PRINT  : PRINT "I AM THINKING OF A THREE-DIGIT NUMBER.  TRY TO GUESS"
110   PRINT "MY NUMBER AND I WILL GIVE YOU CLUES AS FOLLOWS:"
120   PRINT "   PICO   - ONE DIGIT CORRECT BUT IN THE WRONG POSITION"
130   PRINT "   FERMI  - ONE DIGIT CORRECT AND IN THE RIGHT POSITION"
140   PRINT "   BAGELS - NO DIGITS CORRECT"
150   FOR I=1 TO 3
160   A(I)=INT(10*RND())
165   IF I-1=0 THEN 200
170   FOR J=1 TO I-1
180   IF A(I)=A(J) THEN 160
190   NEXT J
200   NEXT I
999   END
